// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.xxxxx.ipidp.awsecsservice.service;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class EcsServiceArgs extends com.pulumi.resources.ResourceArgs {

    public static final EcsServiceArgs Empty = new EcsServiceArgs();

    @Import(name="additionalEnvironment")
    private @Nullable Map<String,String> additionalEnvironment;

    public Optional<Map<String,String>> additionalEnvironment() {
        return Optional.ofNullable(this.additionalEnvironment);
    }

    private EcsServiceArgs() {}

    private EcsServiceArgs(EcsServiceArgs $) {
        this.additionalEnvironment = $.additionalEnvironment;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(EcsServiceArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private EcsServiceArgs $;

        public Builder() {
            $ = new EcsServiceArgs();
        }

        public Builder(EcsServiceArgs defaults) {
            $ = new EcsServiceArgs(Objects.requireNonNull(defaults));
        }

        public Builder additionalEnvironment(@Nullable Map<String,String> additionalEnvironment) {
            $.additionalEnvironment = additionalEnvironment;
            return this;
        }

        public EcsServiceArgs build() {
            return $;
        }
    }

}
