// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

export class CodeDeploy extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'ipidp:aws_ecs_service/blue_green:CodeDeploy';

    /**
     * Returns true if the given object is an instance of CodeDeploy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CodeDeploy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CodeDeploy.__pulumiType;
    }


    /**
     * Create a CodeDeploy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CodeDeployArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
        } else {
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CodeDeploy.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a CodeDeploy resource.
 */
export interface CodeDeployArgs {
}
