// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.mycompany.ipidp.awsecsservice.bluegreen;




public final class CodeDeployArgs extends com.pulumi.resources.ResourceArgs {

    public static final CodeDeployArgs Empty = new CodeDeployArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private CodeDeployArgs $;

        public Builder() {
            $ = new CodeDeployArgs();
        }
        public CodeDeployArgs build() {
            return $;
        }
    }

}
