// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ipidp.AwsEcsService.Service
{
    [IpidpResourceType("ipidp:aws_ecs_service/service:EcrImage")]
    public partial class EcrImage : global::Pulumi.ComponentResource
    {
        /// <summary>
        /// Create a EcrImage resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public EcrImage(string name, EcrImageArgs? args = null, ComponentResourceOptions? options = null)
            : base("ipidp:aws_ecs_service/service:EcrImage", name, args ?? new EcrImageArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://yyyy.xxxxx.io/artifactory/sp-docker/pulumi-ipidp-provider",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class EcrImageArgs : global::Pulumi.ResourceArgs
    {
        public EcrImageArgs()
        {
        }
        public static new EcrImageArgs Empty => new EcrImageArgs();
    }
}
