# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_ipidp.aws_ecs_service as __aws_ecs_service
    aws_ecs_service = __aws_ecs_service
else:
    aws_ecs_service = _utilities.lazy_import('pulumi_ipidp.aws_ecs_service')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "ipidp",
  "mod": "aws_ecs_service/blue_green",
  "fqn": "pulumi_ipidp.aws_ecs_service.blue_green",
  "classes": {
   "ipidp:aws_ecs_service/blue_green:CodeDeploy": "CodeDeploy"
  }
 },
 {
  "pkg": "ipidp",
  "mod": "aws_ecs_service/service",
  "fqn": "pulumi_ipidp.aws_ecs_service.service",
  "classes": {
   "ipidp:aws_ecs_service/service:EcrImage": "EcrImage",
   "ipidp:aws_ecs_service/service:EcsService": "EcsService"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "ipidp",
  "token": "pulumi:providers:ipidp",
  "fqn": "pulumi_ipidp",
  "class": "Provider"
 }
]
"""
)
