// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.mycompany.ipidp.awsecsservice.service;




public final class EcrImageArgs extends com.pulumi.resources.ResourceArgs {

    public static final EcrImageArgs Empty = new EcrImageArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private EcrImageArgs $;

        public Builder() {
            $ = new EcrImageArgs();
        }
        public EcrImageArgs build() {
            return $;
        }
    }

}
