// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.mycompany.ipidp.awsecsservice.service;




public final class EcsServiceArgs extends com.pulumi.resources.ResourceArgs {

    public static final EcsServiceArgs Empty = new EcsServiceArgs();

    public static Builder builder() {
        return new Builder();
    }

    public static final class Builder {
        private EcsServiceArgs $;

        public Builder() {
            $ = new EcsServiceArgs();
        }
        public EcsServiceArgs build() {
            return $;
        }
    }

}
