// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.mycompany.ipidp.awsecsservice.service;

import com.mycompany.ipidp.Utilities;
import com.mycompany.ipidp.awsecsservice.bluegreen.CodeDeploy;
import com.mycompany.ipidp.awsecsservice.service.EcrImage;
import com.mycompany.ipidp.awsecsservice.service.EcsServiceArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="ipidp:aws_ecs_service/service:EcsService")
public class EcsService extends com.pulumi.resources.ComponentResource {
    @Export(name="codeDeploy", refs={CodeDeploy.class}, tree="[0]")
    private Output</* @Nullable */ CodeDeploy> codeDeploy;

    public Output<Optional<CodeDeploy>> codeDeploy() {
        return Codegen.optional(this.codeDeploy);
    }
    @Export(name="ecrImage", refs={EcrImage.class}, tree="[0]")
    private Output</* @Nullable */ EcrImage> ecrImage;

    public Output<Optional<EcrImage>> ecrImage() {
        return Codegen.optional(this.ecrImage);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public EcsService(String name) {
        this(name, EcsServiceArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public EcsService(String name, @Nullable EcsServiceArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public EcsService(String name, @Nullable EcsServiceArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        super("ipidp:aws_ecs_service/service:EcsService", name, args == null ? EcsServiceArgs.Empty : args, makeResourceOptions(options, Codegen.empty()), true);
    }

    private static com.pulumi.resources.ComponentResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.ComponentResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.ComponentResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.ComponentResourceOptions.merge(defaultOptions, options, id);
    }

}
